#
###################################
# Site wide configuration
####################################
#
title:       "apoid jazz"
description: 'Full time bug guy, part time whatever'
url:         # the base hostname & protocol for your site

#
###################################
# Jekyll configuration
####################################
#
timezone:          USA/Sacramento
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: apoid jazz
  avatar: IMG_20150910_184515.jpg
  job: ""
  bio: "musings of an aging hipster naturalist"
  email: nathanjhamlet@gmail.com
  disqus-shortname:
  twitter: nj_hamlet #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: nhamlet #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin:  #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: nastin #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
